import { useState } from 'react';
import { useQuery,useMutation,useQueryClient } from '@tanstack/react-query';
import { api } from '../../../services/api';
import { Badge,Card,Field,PageHead } from '../../common/UI';
import QueryStatus from '../../common/QueryStatus';
import LocationMap from '../../common/LocationMap';
export function AdminRequests(){
  const cache=useQueryClient(),q=useQuery({queryKey:['bin-requests'],queryFn:async()=>({household:await api<any[]>('/admin/bin-requests'),community:await api<any[]>('/admin/community-requests')})});
  const [updates,setUpdates]=useState<Record<string,string>>({});
  const update=useMutation({mutationFn:({kind,id,status}:{kind:string;id:string;status:string})=>api('/admin/'+kind+'/'+id,{status},'PATCH'),onSuccess:()=>cache.invalidateQueries()});
  return <><PageHead title="Bin requests" subtitle="Review household and community requests."/><QueryStatus query={q}/>{update.error&&<p role="alert" className="form-error">{update.error.message}</p>}{q.data&&[['household','Household bins','bin-requests',['REQUESTED','APPROVED','SCHEDULED','DELIVERED','REJECTED']],['community','Community bins','community-requests',['SUBMITTED','UNDER_REVIEW','APPROVED','REJECTED','DEPLOYED']]].map(([key,title,kind,statuses])=><section key={String(key)}><h2>{String(title)}</h2>{!(q.data as any)[String(key)].length&&<Card><p>No requests.</p></Card>}<div className="list">{(q.data as any)[String(key)].map((r:any)=><Card key={r.id}><h3>{r.user.name}</h3><p>{typeof r.address==='string'?r.address:r.address.addressLine}</p><p>{r.reason}</p><p>{r.description}</p><Badge>{r.status}</Badge><div className="button-row"><select aria-label={'Status for '+r.user.name} value={updates[r.id]||r.status} onChange={e=>setUpdates({...updates,[r.id]:e.target.value})}>{(statuses as string[]).map(s=><option key={s}>{s}</option>)}</select><button className="secondary" disabled={update.isPending} onClick={()=>update.mutate({kind:String(kind),id:r.id,status:updates[r.id]||r.status})}>Update status</button></div></Card>)}</div></section>)}</>;
}
export function AdminRewards(){
  const q=useQuery({queryKey:['admin-rewards'],queryFn:()=>api<any[]>('/admin/rewards')}),cache=useQueryClient();
  const [open,setOpen]=useState(false),[form,setForm]=useState({name:'',description:'',pointsCost:10,stock:1});
  const add=useMutation({mutationFn:()=>api('/admin/rewards',form),onSuccess:()=>{setOpen(false);setForm({name:'',description:'',pointsCost:10,stock:1});cache.invalidateQueries({queryKey:['admin-rewards']});}});
  return <><PageHead title="Rewards" action={<button className="button" onClick={()=>setOpen(!open)}>Add new reward</button>}/>{open&&<Card className="section-gap"><form className="form-stack" onSubmit={e=>{e.preventDefault();add.mutate();}}><Field label="Reward name"><input required minLength={2} value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></Field><Field label="Description"><textarea required minLength={3} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></Field><Field label="Points required"><input required type="number" min={1} value={form.pointsCost} onChange={e=>setForm({...form,pointsCost:Number(e.target.value)})}/></Field><Field label="Stock"><input required type="number" min={0} value={form.stock} onChange={e=>setForm({...form,stock:Number(e.target.value)})}/></Field>{add.error&&<p className="form-error" role="alert">{add.error.message}</p>}<button className="button" disabled={add.isPending}>Save reward</button></form></Card>}<QueryStatus query={q}/>{q.data&&!q.data.length&&<Card><p>No rewards offered yet.</p></Card>}<div className="grid3">{q.data?.map(r=><Card key={r.id}><h3>{r.name}</h3><p>{r.description}</p><p>{r.pointsCost} points · {r.stock} available</p></Card>)}</div></>;
}
export function AdminHotspots(){
  const q=useQuery({queryKey:['hotspots'],queryFn:()=>api<any[]>('/hotspots')}),cache=useQueryClient();
  const [selected,setSelected]=useState<string>(),[type,setType]=useState('SCHEDULE_CLEANUP'),[description,setDescription]=useState('');
  const add=useMutation({mutationFn:()=>api('/admin/hotspots/'+selected+'/actions',{type,description}),onSuccess:()=>{setDescription('');cache.invalidateQueries({queryKey:['hotspots']});}});
  return <><PageHead title="Waste hotspots" subtitle="Locations identified from actual resident reports."/><QueryStatus query={q}/>{q.data&&!q.data.length&&<Card><p>No hotspots have been identified.</p></Card>}{!!q.data?.length&&<><LocationMap points={q.data.map(h=>({...h,name:h.address}))} selectedId={selected} onSelect={setSelected}/><div className="grid3 bin-list">{q.data.map(h=><Card key={h.id}><h3>{h.address}</h3><Badge>{h.priority}</Badge><p>{h.complaintCount} reports · {h.status}</p>{h.actions.map((a:any)=><p key={a.id}>{a.type}: {a.description}</p>)}<button className="secondary" onClick={()=>{setSelected(h.id);add.reset();}}>Plan action</button></Card>)}</div>{selected&&<Card className="section-gap"><form className="form-stack" onSubmit={e=>{e.preventDefault();add.mutate();}}><h2>Action for {q.data.find(h=>h.id===selected)?.address}</h2><Field label="Action type"><select value={type} onChange={e=>setType(e.target.value)}>{['SCHEDULE_CLEANUP','DEPLOY_COMMUNITY_BIN','DEPLOY_BOARD','SEND_MANAGER','CONTACT_NEARBY_HOUSEHOLDS'].map(t=><option key={t}>{t}</option>)}</select></Field><Field label="Action details"><textarea required minLength={3} value={description} onChange={e=>setDescription(e.target.value)}/></Field>{add.error&&<p role="alert" className="form-error">{add.error.message}</p>}{add.isSuccess&&<p role="status">Action saved.</p>}<button className="button" disabled={add.isPending}>Create action</button></form></Card>}</>}</>;
}

