import { useState } from 'react';
import { useMutation,useQuery,useQueryClient } from '@tanstack/react-query';
import { Link } from 'react-router-dom';
import { api } from '../../../services/api';
import { Badge,Card,Field,PageHead } from '../../common/UI';
import QueryStatus from '../../common/QueryStatus';
import LocationMap,{Location} from '../../common/LocationMap';
import AddressEditor,{AddressDraft,emptyAddress} from '../../common/AddressEditor';
export function AdminTrucks(){
  const cache=useQueryClient(),q=useQuery({queryKey:['trucks'],queryFn:()=>api<any[]>('/admin/trucks')}),users=useQuery({queryKey:['admin-users'],queryFn:()=>api<any[]>('/admin/users')});
  const [form,setForm]=useState<any>(null),[point,setPoint]=useState<Location>();
  const save=useMutation({mutationFn:()=>{if(!point)throw new Error('Choose the truck’s current location on the map');return api('/admin/trucks'+(form.id?'/'+form.id:''),{name:form.name,registrationNumber:form.registrationNumber,capacity:Number(form.capacity),driverId:form.driverId||null,active:form.active,currentLatitude:point.latitude,currentLongitude:point.longitude},form.id?'PUT':'POST');},onSuccess:()=>{setForm(null);cache.invalidateQueries({queryKey:['trucks']});cache.invalidateQueries({queryKey:['admin-users']});cache.invalidateQueries({queryKey:['planning']});cache.invalidateQueries({queryKey:['admin-dashboard']});}});
  function edit(t?:any){save.reset();setForm(t?{...t,driverId:t.driverId||''}:{name:'',registrationNumber:'',capacity:20,driverId:'',active:true});setPoint(t?{latitude:t.currentLatitude,longitude:t.currentLongitude}:undefined);}
  return <><PageHead title="Trucks" subtitle="Set each truck’s driver, starting location and maximum stops per run." action={<button className="button" onClick={()=>edit()}>Add new truck</button>}/>
    {form&&<form className="section-gap" onSubmit={e=>{e.preventDefault();save.mutate();}}><div className="two"><Card><div className="form-stack"><h2>{form.id?'Edit / assign truck':'Add truck'}</h2><Field label="Truck name"><input required minLength={2} value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></Field><Field label="Registration number"><input required minLength={3} value={form.registrationNumber} onChange={e=>setForm({...form,registrationNumber:e.target.value})}/></Field><Field label="Maximum stops per run"><input type="number" min={1} max={500} required value={form.capacity} onChange={e=>setForm({...form,capacity:e.target.value})}/></Field><Field label="Assigned driver"><select value={form.driverId} onChange={e=>setForm({...form,driverId:e.target.value})}><option value="">Not assigned</option>{users.data?.filter(u=>u.role==='WORKER'&&(!u.assignedTruck||u.assignedTruck.id===form.id)).map(u=><option key={u.id} value={u.id}>{u.name} · {u.email}</option>)}</select></Field><p><Link className="text-button" to="/admin/users">Create a driver account</Link> if the driver is not listed.</p><label className="check-row"><input type="checkbox" checked={form.active} onChange={e=>setForm({...form,active:e.target.checked})}/>Available for collection work</label><p>{point?'Starting position: '+point.latitude.toFixed(5)+', '+point.longitude.toFixed(5):'Select a starting position on the map.'}</p>{save.error&&<p className="form-error" role="alert">{save.error.message}</p>}<div className="button-row"><button className="button" disabled={save.isPending}>Save truck</button><button className="secondary" type="button" onClick={()=>setForm(null)}>Cancel</button></div></div></Card><LocationMap value={point} onChange={setPoint}/></div></form>}
    <QueryStatus query={q}/><QueryStatus query={users}/>{q.data&&!q.data.length&&<Card><p>No trucks added yet. Add a truck, assign a driver, and choose its starting location.</p></Card>}
    <div className="grid3">{q.data?.map(t=><Card key={t.id}><Badge>{t.active?t.status:'INACTIVE'}</Badge><h3>{t.name}</h3><p>{t.registrationNumber}</p><p>Driver: {t.driver?.name||'Not assigned'}</p><p>{t.capacity} stops per run</p><button className="secondary" onClick={()=>edit(t)}>Edit / assign driver</button></Card>)}</div>
  </>;
}
export function AdminBins(){
  const cache=useQueryClient(),q=useQuery({queryKey:['admin-bins'],queryFn:()=>api<any[]>('/admin/bins')});
  const [draft,setDraft]=useState<AddressDraft|null>(null),[form,setForm]=useState<any>({type:'PUBLIC',size:'120L',status:'ACTIVE',needsCollection:true}),[selected,setSelected]=useState<string>();
  const save=useMutation({mutationFn:()=>{if(draft?.latitude===undefined||draft.longitude===undefined)throw new Error('Choose a bin location on the map');return api('/admin/bins'+(form.id?'/'+form.id:''),{...form,address:draft.addressLine,area:draft.area,landmark:draft.landmark,accessNotes:draft.accessNotes,latitude:draft.latitude,longitude:draft.longitude},form.id?'PUT':'POST');},onSuccess:()=>{setDraft(null);cache.invalidateQueries({queryKey:['admin-bins']});cache.invalidateQueries({queryKey:['bins']});cache.invalidateQueries({queryKey:['planning']});cache.invalidateQueries({queryKey:['admin-dashboard']});}});
  function edit(b?:any){save.reset();setForm(b?{...b}:{type:'PUBLIC',size:'120L',status:'ACTIVE',needsCollection:true});setDraft(b?{...emptyAddress(),addressLine:b.address,area:b.area||'',landmark:b.landmark||'',accessNotes:b.accessNotes||'',latitude:b.latitude,longitude:b.longitude}:emptyAddress());}
  return <><PageHead title="Bins" subtitle="Register real bin locations and mark which bins need collection." action={<button className="button" onClick={()=>edit()}>Add new bin</button>}/>
    {draft&&<form className="section-gap" onSubmit={e=>{e.preventDefault();save.mutate();}}><AddressEditor value={draft} onChange={setDraft}><Field label="Bin type"><select value={form.type} onChange={e=>setForm({...form,type:e.target.value})}><option value="PUBLIC">Public</option><option value="COMMUNITY">Community</option></select></Field><Field label="Bin size"><input required value={form.size} onChange={e=>setForm({...form,size:e.target.value})}/></Field><Field label="Bin status"><select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}>{['ACTIVE','DAMAGED','REMOVED'].map(s=><option key={s}>{s}</option>)}</select></Field><label className="check-row"><input type="checkbox" checked={form.needsCollection} onChange={e=>setForm({...form,needsCollection:e.target.checked})}/>Needs collection</label>{save.error&&<p className="form-error" role="alert">{save.error.message}</p>}<div className="button-row"><button className="button" disabled={save.isPending}>Save bin</button><button className="secondary" type="button" onClick={()=>setDraft(null)}>Cancel</button></div></AddressEditor></form>}
    <QueryStatus query={q}/>{q.data&&!q.data.length&&<Card><p>No bins have been registered. Add a bin using its actual map location.</p></Card>}
    {!!q.data?.length&&<LocationMap points={q.data.map(b=>({...b,name:b.address}))} selectedId={selected} onSelect={setSelected}/>}
    <div className="grid3 bin-list">{q.data?.map(b=><Card key={b.id} className={selected===b.id?'selected-bin':''}><Badge>{b.status}</Badge><h3>{b.address}</h3><p>{b.area}</p><p>{b.type} · {b.size}</p><p>{b.needsCollection?'Needs collection':'Collection not currently needed'}</p><div className="button-row"><button className="secondary" onClick={()=>{setSelected(b.id);document.querySelector('.location-map')?.scrollIntoView({behavior:'smooth'});}}>View location</button><button className="secondary" onClick={()=>edit(b)}>Edit bin</button></div></Card>)}</div>
  </>;
}

