import { Router } from 'express';import { z } from 'zod';import { prisma } from '../../config/prisma';import { asyncHandler,AppError } from '../../lib/http';import { requireAuth } from '../../middleware/auth';import { distanceMeters } from '../../services/geo.service';
const r=Router();r.use(requireAuth);
r.get('/users/me',asyncHandler(async(req,res)=>res.json(await prisma.user.findUniqueOrThrow({where:{id:req.auth!.userId},select:{id:true,name:true,email:true,phone:true,role:true,trashPoints:true,createdAt:true}}))));
r.put('/users/me',asyncHandler(async(req,res)=>{const data=z.object({name:z.string().min(2).optional(),phone:z.string().nullable().optional()}).parse(req.body);res.json(await prisma.user.update({where:{id:req.auth!.userId},data,select:{id:true,name:true,email:true,phone:true,role:true,trashPoints:true}}));}));
const address=z.object({addressLine:z.string().min(3),area:z.string().min(2),landmark:z.string().optional(),latitude:z.number().gte(-90).lte(90),longitude:z.number().gte(-180).lte(180),accessNotes:z.string().optional()});
r.post('/addresses',asyncHandler(async(req,res)=>res.status(201).json(await prisma.address.create({data:{...address.parse(req.body),userId:req.auth!.userId}}))));r.get('/addresses',asyncHandler(async(req,res)=>res.json(await prisma.address.findMany({where:{userId:req.auth!.userId}}))));r.put('/addresses/:id',asyncHandler(async(req,res)=>{const old=await prisma.address.findFirst({where:{id:req.params.id,userId:req.auth!.userId}});if(!old)throw new AppError(404,'Address not found');res.json(await prisma.address.update({where:{id:old.id},data:address.partial().parse(req.body)}));}));
r.post('/bin-requests',asyncHandler(async(req,res)=>{const data=z.object({type:z.enum(['HOUSEHOLD','COMMUNITY','PUBLIC']).default('HOUSEHOLD'),size:z.string().min(1),reason:z.string().min(3),addressId:z.string()}).parse(req.body);const a=await prisma.address.findFirst({where:{id:data.addressId,userId:req.auth!.userId}});if(!a)throw new AppError(404,'Address not found');res.status(201).json(await prisma.binRequest.create({data:{...data,userId:req.auth!.userId}}));}));r.get('/bin-requests/my',asyncHandler(async(req,res)=>res.json(await prisma.binRequest.findMany({where:{userId:req.auth!.userId},include:{address:true},orderBy:{createdAt:'desc'}}))));r.get('/bin-requests/:id',asyncHandler(async(req,res)=>{const x=await prisma.binRequest.findFirst({where:{id:req.params.id,...(req.auth!.role==='ADMIN'?{}:{userId:req.auth!.userId})},include:{address:true}});if(!x)throw new AppError(404,'Request not found');res.json(x);}));
r.get('/bins/nearby',asyncHandler(async(req,res)=>{const q=z.object({lat:z.coerce.number(),lng:z.coerce.number(),radius:z.coerce.number().positive().max(50000).default(2000)}).parse(req.query);const bins=await prisma.bin.findMany({where:{status:'ACTIVE'}});res.json(bins.map(bin=>({...bin,distanceMeters:distanceMeters({latitude:q.lat,longitude:q.lng},bin)})).filter(x=>x.distanceMeters<=q.radius).sort((a,b)=>a.distanceMeters-b.distanceMeters));}));
export default r;
