import { test,expect,Page } from '@playwright/test';
import { createRequire } from 'node:module';
import path from 'node:path';
const requireBackend=createRequire(path.resolve('../backend/package.json'));
requireBackend('dotenv').config({path:'../backend/.env',quiet:true});
const {PrismaClient}=requireBackend('@prisma/client'),bcrypt=requireBackend('bcryptjs');
const db=new PrismaClient(),tag='flow'+Date.now(),password='BrowserPass123';
const email=(name:string)=>tag+'-'+name+'@example.test';
const userIds:string[]=[],truckIds:string[]=[],binIds:string[]=[];
async function signIn(page:Page,who='admin',driver=false){
  await page.goto(driver?'/auth/driver':'/auth/login',{waitUntil:'domcontentloaded'});
  await page.getByLabel('Email',{exact:true}).click();await page.getByLabel('Email',{exact:true}).fill(email(who));
  await page.getByLabel('Password',{exact:true}).click();await page.getByLabel('Password',{exact:true}).fill(password);
  const response=page.waitForResponse(r=>r.url().endsWith(driver?'/api/auth/driver/login':'/api/auth/login'));
  await page.getByRole('button',{name:'Sign in',exact:true}).click();
  expect((await response).status()).toBe(200);
}
async function search(page:Page,query:string){
  await page.getByRole('textbox',{name:'Search for a place'}).fill(query);
  await page.getByRole('button',{name:'Search',exact:true}).click();
  await page.locator('.map-results button').first().click();
}
test.beforeAll(async()=>{
  const admin=await db.user.create({data:{name:tag+' Administrator',email:email('admin'),role:'ADMIN',passwordHash:await bcrypt.hash(password,10)}});userIds.push(admin.id);
});
test.beforeEach(async({page})=>{
  await page.route('https://fonts.googleapis.com/**',r=>r.abort());
  await page.route('https://photon.komoot.io/**',async r=>{
    const url=new URL(r.request().url()),q=url.searchParams.get('q')||'Selected point';
    const west=q.toLowerCase().includes('west'),east=q.toLowerCase().includes('east');
    const lat=Number(url.searchParams.get('lat')||12),lon=Number(url.searchParams.get('lon')||(east?78:west?77:77.5));
    await r.fulfill({json:{features:[{geometry:{coordinates:[lon,lat]},properties:{name:q,city:'Test City',district:'Test Area',...(url.pathname.includes('reverse')?{street:'Map Street',housenumber:'14'}:{})}}]}});
  });
});
test.afterAll(async()=>{
  const users=await db.user.findMany({where:{email:{in:['admin','resident','west','east','lookup'].map(email)}},select:{id:true}});
  const ids=users.map((u:any)=>u.id);
  const trucks=await db.truck.findMany({where:{registrationNumber:{in:[tag+'-WEST',tag+'-EAST']}},select:{id:true}});
  const tids=trucks.map((t:any)=>t.id);
  const routes=await db.route.findMany({where:{truckId:{in:tids}},select:{id:true}}),rids=routes.map((r:any)=>r.id);
  await db.routeStop.deleteMany({where:{routeId:{in:rids}}});
  await db.pickupRequest.deleteMany({where:{userId:{in:ids}}});
  await db.route.deleteMany({where:{id:{in:rids}}});
  await db.truck.deleteMany({where:{id:{in:tids}}});
  await db.bin.deleteMany({where:{address:{in:[tag+' West bin',tag+' East bin']}}});
  await db.trashPointTransaction.deleteMany({where:{userId:{in:ids}}});
  await db.address.deleteMany({where:{userId:{in:ids}}});
  await db.user.deleteMany({where:{id:{in:ids}}});
  await db.$disconnect();
});
test('registration, profile photo/phone, map address, saved pickup, breadcrumbs and logout confirmation',async({page})=>{
  await page.goto('/auth/register',{waitUntil:'domcontentloaded'});
  await expect(page.getByLabel('Phone',{exact:true})).toHaveCount(0);
  await expect(page.getByLabel('Address',{exact:true})).toHaveCount(0);
  await page.getByLabel('Full name').fill(tag+' Resident');
  await page.getByLabel('Email',{exact:true}).click();await page.getByLabel('Email',{exact:true}).fill(email('resident'));
  await page.getByLabel('Password',{exact:true}).click();await page.getByLabel('Password',{exact:true}).fill(password);
  await page.getByLabel('Confirm password').fill(password);
  const registered=page.waitForResponse(r=>r.url().endsWith('/api/auth/register'));
  await page.getByRole('button',{name:'Create account',exact:true}).click();
  const r=await registered;expect(r.status()).toBe(201);expect(r.request().postDataJSON()).not.toHaveProperty('phone');
  const resident=(await r.json()).user;userIds.push(resident.id);
  await page.getByRole('link',{name:'My profile',exact:true}).click();
  await page.getByLabel('Phone (optional)').fill('9876543210');
  const photo=await page.evaluate(()=>{const c=document.createElement('canvas');c.width=20;c.height=20;const ctx=c.getContext('2d')!;ctx.fillStyle='green';ctx.fillRect(0,0,20,20);return c.toDataURL('image/png').split(',')[1];});
  await page.getByLabel('Profile photo',{exact:true}).setInputFiles({name:'profile.png',mimeType:'image/png',buffer:Buffer.from(photo,'base64')});
  const savedProfile=page.waitForResponse(r=>r.url().endsWith('/api/users/me')&&r.request().method()==='PUT');
  await page.getByRole('button',{name:'Save profile'}).click();expect((await savedProfile).status()).toBe(200);
  await page.getByRole('button',{name:'Add address',exact:true}).click();
  await page.locator('.leaflet-map').click({position:{x:160,y:140}});
  await expect(page.getByLabel('Address',{exact:true})).toHaveValue('14 Map Street, Test Area, Test City');
  await expect(page.getByLabel('Area / neighborhood')).toHaveValue('Test Area');
  await page.getByLabel('Address label').fill('Home '+tag);
  await page.getByLabel('Landmark (optional)').fill('Blue gate');
  await page.getByLabel('Access instructions (optional)').fill('Ring the bell');
  await page.getByRole('button',{name:'Save address',exact:true}).click();
  await expect(page.getByRole('status').filter({hasText:'Address saved'})).toBeVisible();
  const address=await db.address.findFirstOrThrow({where:{userId:resident.id}});
  await page.goto('/app/pickups/new',{waitUntil:'domcontentloaded'});
  await expect(page.getByLabel('Saved address')).toHaveValue(address.id);
  await expect(page.getByLabel('Landmark (optional)')).toHaveValue('Blue gate');
  const pickupResponse=page.waitForResponse(r=>r.url().endsWith('/api/pickups')&&r.request().method()==='POST');
  await page.getByRole('button',{name:'Submit request'}).click();
  const pickup=await pickupResponse;expect(pickup.status()).toBe(201);expect(pickup.request().postDataJSON().addressId).toBe(address.id);
  await page.getByRole('link',{name:'View my pickups'}).click();
  await page.getByRole('link',{name:'View details'}).first().click();
  await page.getByRole('navigation',{name:'Breadcrumb'}).getByRole('link',{name:'Pickups',exact:true}).click();
  await expect(page).toHaveURL(/app\/pickups$/);
  page.once('dialog',d=>d.dismiss());await page.getByRole('button',{name:'Sign out'}).click();await expect(page).toHaveURL(/app\/pickups$/);
  page.once('dialog',d=>d.accept());await page.getByRole('button',{name:'Sign out'}).click();
  await expect(page.getByLabel('Email',{exact:true})).toHaveValue('');
  await expect(page.getByLabel('Password',{exact:true})).toHaveValue('');
  const saved=await db.user.findUnique({where:{id:resident.id}});expect(saved.phone).toBe('9876543210');expect(saved.photoUrl).toMatch(/^data:image\/jpeg;base64,/);
});
test('admin user details, adding trucks/bins, grouped routes and driver collection',async({page})=>{
  await signIn(page);
  for(const side of ['west','east']){
    await page.goto('/admin/users',{waitUntil:'domcontentloaded'});
    await page.getByRole('button',{name:'Add new user'}).click();
    await page.getByLabel('Full name').fill(tag+' '+side+' driver');
    await page.getByLabel('Email',{exact:true}).click();await page.getByLabel('Email',{exact:true}).fill(email(side));
    await page.getByLabel('Initial password').fill(password);
    const created=page.waitForResponse(r=>r.url().endsWith('/api/admin/users')&&r.request().method()==='POST');
    await page.getByRole('button',{name:'Create account',exact:true}).click();
    expect((await created).status()).toBe(201);
    const row=page.locator('.request').filter({hasText:email(side)});
    await row.getByRole('link',{name:'View details'}).click();
    await expect(page.getByRole('heading',{name:tag+' '+side+' driver'})).toBeVisible();
    const driver=await db.user.findUniqueOrThrow({where:{email:email(side)}});userIds.push(driver.id);
    await page.goto('/admin/trucks',{waitUntil:'domcontentloaded'});
    await page.getByRole('button',{name:'Add new truck'}).click();
    await page.getByLabel('Truck name').fill(tag+' '+side+' truck');
    await page.getByLabel('Registration number').fill(tag+'-'+side.toUpperCase());
    await page.getByLabel('Maximum stops per run').fill('2');
    await page.getByLabel('Assigned driver').selectOption(driver.id);
    await search(page,side+' depot');
    const truckResponse=page.waitForResponse(r=>r.url().endsWith('/api/admin/trucks')&&r.request().method()==='POST');
    await page.getByRole('button',{name:'Save truck'}).click();
    const tr=await truckResponse;expect(tr.status()).toBe(201);truckIds.push((await tr.json()).id);
    await page.goto('/admin/bins',{waitUntil:'domcontentloaded'});
    await page.getByRole('button',{name:'Add new bin'}).click();
    await search(page,side+' bin');
    await expect(page.getByLabel('Area / neighborhood')).toHaveValue('Test Area');
    await page.getByLabel('Address',{exact:true}).fill(tag+' '+(side==='west'?'West':'East')+' bin');
    const binResponse=page.waitForResponse(r=>r.url().endsWith('/api/admin/bins')&&r.request().method()==='POST');
    await page.getByRole('button',{name:'Save bin'}).click();
    const br=await binResponse;expect(br.status()).toBe(201);binIds.push((await br.json()).id);
  }
  await page.goto('/admin/routes/new',{waitUntil:'domcontentloaded'});
  for(const side of ['west','east'])await page.getByLabel(tag+' '+side+' truck',{exact:false}).check();
  await page.getByLabel(tag+' West bin',{exact:false}).check();await page.getByLabel(tag+' East bin',{exact:false}).check();
  await page.getByRole('button',{name:'Preview routes'}).click();
  await expect(page.getByRole('heading',{name:'Review assignments'})).toBeVisible();
  const assignment=page.waitForResponse(r=>r.url().endsWith('/api/routes/generate'));
  await page.getByRole('button',{name:'Assign routes to drivers'}).click();
  const assigned=await assignment;expect(assigned.status()).toBe(201);const routes=(await assigned.json()).routes;expect(routes).toHaveLength(2);
  expect(routes.find((r:any)=>r.truckId===truckIds[0]).stops[0].binId).toBe(binIds[0]);
  expect(routes.find((r:any)=>r.truckId===truckIds[1]).stops[0].binId).toBe(binIds[1]);
  page.once('dialog',d=>d.accept());await page.getByRole('button',{name:'Sign out'}).click();
  await page.getByLabel('Email',{exact:true}).click();await page.getByLabel('Email',{exact:true}).fill(email('west'));await page.getByLabel('Password',{exact:true}).click();await page.getByLabel('Password',{exact:true}).fill(password);
  await page.getByRole('button',{name:'Sign in',exact:true}).click();
  await expect(page.getByRole('alert')).toContainText('truck driver sign-in');
  await page.getByRole('link',{name:'Truck driver sign in'}).click();
  await expect(page.getByLabel('Email',{exact:true})).toHaveValue('');
  await signIn(page,'west',true);
  await page.getByRole('link',{name:'Open route'}).click();
  await expect(page.getByRole('link',{name:'Navigate to stop'})).toHaveAttribute('href',/openstreetmap.org\/directions/);
  await page.getByRole('button',{name:'Start route',exact:true}).click();
  await expect(page.getByText('IN_PROGRESS',{exact:true}).first()).toBeVisible();
  const completed=page.waitForResponse(r=>r.url().includes('/worker/stops/')&&r.url().endsWith('/complete'));
  page.once('dialog',d=>d.accept());await page.getByRole('button',{name:'Confirm collection'}).click();
  expect((await completed).status()).toBe(200);
  await expect(page.getByText('Route closed.',{exact:false})).toBeVisible();
  expect((await db.bin.findUnique({where:{id:binIds[0]}})).needsCollection).toBe(false);
  await page.screenshot({path:'test-results/driver-route.png',fullPage:true});
});
test('address lookup failures allow manual entry and do not leave old address text',async({page})=>{
  await signIn(page,'resident');
  await page.goto('/profile',{waitUntil:'domcontentloaded'});
  await page.getByRole('button',{name:'Add address',exact:true}).click();
  await search(page,'First address');
  await expect(page.getByLabel('Address',{exact:true})).toHaveValue('First address, Test Area, Test City');
  await page.route('https://photon.komoot.io/reverse**',r=>r.fulfill({status:503}));
  await page.locator('.leaflet-map').click({position:{x:180,y:160}});
  await expect(page.getByLabel('Address',{exact:true})).toHaveValue('');
  await expect(page.getByText('Address lookup is unavailable.',{exact:false})).toBeVisible();
  await page.getByLabel('Address',{exact:true}).fill('Manual address');
  await page.getByLabel('Area / neighborhood').fill('Manual area');
  await expect(page.getByLabel('Address',{exact:true})).toHaveValue('Manual address');
});

